# https://nicolas-van.github.io/easy-markdown-to-github-pages/

title: Documentation Pixel Circus
description: "Documentation des processus et des outils utilisés par l'agence"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-midnight
